version: "3"
services:
  client:
    image: "shallon041/client"
    mem_limit: 128m
    hostname: client
  server:
    image: "shallon041/server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  nginx:
    image: "shallon041/nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
