version: "3"
services:
  mongo:
    image: shallon041/mongodb:latest
    build: ./
    ports:
      - 27017:27017

  server:
    image: shallon041/server
    build: ./server/
    ports:
      - "5000:8000"
    depends_on:
      - "mongo"

  client:
    image: shallon041/client
    mem_limit: 128m
    ports:
      - "3000:3000"
    depends_on:
      - "server"
    links:
      - server

  nginx:
    image: shallon041/nginx
    build: ./nginx/
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
