version: "3"
services:
  client:
    image: "shallon041/client"
    mem_limit: 128m
    hostname: client
  server:
    image: "shallon041/server"
    mem_limit: 128m
    hostname: api
  nginx:
    image: "shallon041/nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
